[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
petai = "47WMeQhwKsEr9RgTxiTupUJKtohL9Rd1A5GyemBqsbKH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/olex/.config/solana/id.json"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "mpl_token_metadata.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
